### ISSUE TITLE
Does not run under python 3.8

### ISSUE THREAD

**Issue by jangeador** [lakhanmankani/wifi_qrcode_generator#4]
I was trying to use the library with python 3.8 and it complained about the password parameter which has the following code:

```py3
def wifi_code(ssid: str, hidden: bool, authentication_type: str,
              password: str | None = None) -> str:
```

It was complaining in particular about the `|` in the `password` parameter. There is another function in the same file which has the same code

```py3
def wifi_qrcode(ssid: str, hidden: bool, authentication_type: str, password: str | None = None,
                **kwargs) -> qrcode.QRCode:
```

**Comment by lakhanmankani** [comment]
Thanks for raising this. Python 3.8 support was droped with release of v1.0.0. I have decided to add back support for it seeing as it is still widely used. This PR should fix the issue https://github.com/lakhanmankani/wifi_qrcode_generator/pull/6
