### ISSUE TITLE
How can I use a Dollar-Character in my WiFi-Password?

### ISSUE THREAD

**Issue by KayGundhardt** [lakhanmankani/wifi_qrcode_generator#7]
Hi there,

first oft all: thank you very much for your work :) Then I would l’île to ask how to use a 

`$`

in a WiFi-Password like

`wifi-qrcode-generator -s "Home WiFi" -p "very complicated pa$$word with a $" -a WPA -o qr.png -P`

to be inserted in my QR-Code? I know that the Dollar Character is forbidden in python but it isn't in WiFi-Passwords: so - is there any way to insert? Quote somehow?

Any help would be really appreciated! :) 

Thank you!

Kay

**Comment by lakhanmankani** [comment]
Hi, the command you have posted works fine for me on the cli. What is the issue you are encountering? And as far as I'm aware, Python has no issues with dollar signs in strings.

Perhaps the issue is with your shell not escaping the dollar. In which case I would try 
```bash
wifi-qrcode-generator -s "Home WiFi" -p "very complicated pa\$\$word with a \$" -a WPA -o qr.png -P
```

**Comment by KayGundhardt** [comment]
That's it: definitely not a code issue but rather a lack of shell knowledge... 

🙈 I’m sorry!

Anyway: maybe it helps one or the other here - thanks a lot!

**Comment by KayGundhardt** [comment]
That's it: definitely not a code issue but rather a lack of shell knowledge...

🙈 I’m sorry!

Anyway: maybe it helps one or the other here - thanks a lot!
